# Generated by Django 5.2.8 on 2025-11-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
